---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- LocalHost:
    - Plex:
        href: http://10.0.0.200:32400
        siteMonitor: http://10.0.0.200:32400
    - Nas:
        href: http://10.0.0.200:5000
        siteMonitor: http://10.0.0.200:5000
    - Portainer:
        href: http://10.0.0.200:9000
        siteMonitor: http://10.0.0.200:9000
    - Blog-memos:
        href: http://10.0.0.200:5240
        siteMonitor: http://10.0.0.200:5240
    - Edge:
        href: http://10.0.0.200:3429
        siteMonitor: http://10.0.0.200:3429
    - Remote-Guacamole:
        href: http://10.0.0.200:8348
        siteMonitor: http://10.0.0.200:8348
    - Code server:
        href: http://10.0.0.200:8377
        siteMonitor: http://10.0.0.200:8377
    - Lynx:
        href: http://10.0.0.200:3485
        siteMonitor: http://10.0.0.200:3485
    - Synology Music:
        href: http://10.0.0.200:8800
        siteMonitor: http://10.0.0.200:8800
    - WordPress:
        href: http://10.0.0.200:8181
        siteMonitor: http://10.0.0.200:8181
    - Hommar:
        href: http://10.0.0.200:4755
        siteMonitor: http://10.0.0.200:4755
    - Paperless:
        href: http://10.0.0.200:8777
        siteMonitor: http://10.0.0.200:8777
    - Synology Photo:
        href: http://10.0.0.200:5080
        siteMonitor: http://10.0.0.200:5080
    - Shorlink-Slash:
        href: http://10.0.0.200:5231
        siteMonitor: http://10.0.0.200:5231
    - Komga:
        href: http://10.0.0.200
        siteMonitor: http://10.0.0.200

- Synology:
    - Plex:
        href: https://plex.cherryken.com
    - Nas:
        href: https://nas.cherryken.com
    - Portainer:
        href: https://portainer.cherryken.com
    - Blog-memos:
        href: https://blog.cherryken.com
    - Edge:
        href: https://edge.cherryken.com
    - Remote-Guacamole:
        href: https://remote.cherryken.com
    - Code server:
        href: https://code.cherryken.com
    - Lynx:
        href: https://link.cherryken.com
    - Synology Music:
        href: https://music.cherryken.com
    - WordPress:
        href: https://cherryken.com
    - Hommar:
        href: https://home.cherryken.com
    - Paperless:
        href: https://paperless.cherryken.com
    - Synology Photo:
        href: https://photo.cherryken.com
    - Shorlink-Slash:
        href: https://slash.cherryken.com
    - Komga:
        href: https://komga.cherryken.com

