---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Localhosts:
    - Plex:
        href: http://10.0.0.200:32400
        siteMonitor: http://10.0.0.200:32400
    - Nas:
        href: http://10.0.0.200:5000
        siteMonitor: http://10.0.0.200:5000
    - Portainer:
        href: http://10.0.0.200:9000
        siteMonitor: http://10.0.0.200:9000
    - Blogmemos:
        href: http://10.0.0.200:5240
        siteMonitor: http://10.0.0.200:5240
    - Edge:
        href: http://10.0.0.200:3429
        siteMonitor: http://10.0.0.200:3429
    - RemoteGuacamole:
        href: http://10.0.0.200:8348
        siteMonitor: http://10.0.0.200:8348
    - CodeServer:
        href: http://10.0.0.200:8377
        siteMonitor: http://10.0.0.200:8377
    - Lynx:
        href: http://10.0.0.200:3485
        siteMonitor: http://10.0.0.200:3485
    - SynologyMusic:
        href: http://10.0.0.200:8800
        siteMonitor: http://10.0.0.200:8800
    - WordPress:
        href: http://10.0.0.200:8181
        siteMonitor: http://10.0.0.200:8181
    - Hommar:
        href: http://10.0.0.200:4755
        siteMonitor: http://10.0.0.200:4755
    - Paperless:
        href: http://10.0.0.200:8777
        siteMonitor: http://10.0.0.200:8777
    - SynologyPhoto:
        href: http://10.0.0.200:5080
        siteMonitor: http://10.0.0.200:5080
    - ShorlinkSlash:
        href: http://10.0.0.200:5231
        siteMonitor: http://10.0.0.200:5231
    - Komga:
        href: http://10.0.0.200
        siteMonitor: http://10.0.0.200

- Synology:
    - Plex:
        href: https://plex.dpham.one
    - Nas:
        href: https://nas.dpham.one
    - Portainer:
        href: https://portainer.dpham.one
    - Blogmemos:
        href: https://blog.dpham.one
    - Edge:
        href: https://edge.dpham.one
    - RemoteGuacamole:
        href: https://remote.dpham.one
    - CodeServer:
        href: https://code.dpham.one
    - Lynx:
        href: https://link.dpham.one
    - SynologyMusic:
        href: https://music.dpham.one
    - WordPress:
        href: https://dpham.one
    - Hommar:
        href: https://home.dpham.one
    - Paperless:
        href: https://paperless.dpham.one
    - SynologyPhoto:
        href: https://photo.dpham.one
    - ShorlinkSlash:
        href: https://slash.dpham.one
    - Komga:
        href: https://komga.dpham.one

        test

